name: AdminGUI
version: '${project.version}'
main: maksinus.admingui.AdminGUI
api-version: 1.16
softdepend: [LuckPerms]
commands:
  admingui:
    aliases: [agui, admin]
    description: Admin gui
    usage: /admingui
  asetspawn:
    description: Set spawn
    usage: /asetspawn
